version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-ad-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./media:/app/media
      - ./uploads:/app/uploads
      - ./images:/app/images
      - ./logs:/app/logs
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: telegram-ad-bot-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-password}
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:alpine
    container_name: telegram-ad-bot-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
  redis_data: 